import React, { useState } from 'react'
import { FileText, ExternalLink, Save, Share, Download } from 'lucide-react'
import ActionStatus from './ActionStatus'
import { useAuth } from '../context/AuthContext'
import { generateSummary } from '../services/openaiService'
import { saveSummary } from '../services/supabaseService'
import { hasReachedSummaryLimit } from '../services/subscriptionService'

export default function PaperSummarizer({ onSummaryCreated }) {
  const [url, setUrl] = useState('')
  const [status, setStatus] = useState('idle')
  const [errorMessage, setErrorMessage] = useState('')
  const [summary, setSummary] = useState(null)
  const { user, incrementSummariesUsed } = useAuth()

  // Check if user has reached their summary limit
  const reachedLimit = hasReachedSummaryLimit(user)

  const handleSubmit = async (e) => {
    e.preventDefault()
    if (!url.trim()) return

    if (reachedLimit) {
      setStatus('error')
      setErrorMessage("You've reached your monthly summary limit. Please upgrade your plan to continue.")
      return
    }

    setStatus('pending')
    setSummary(null)
    setErrorMessage('')

    try {
      // Generate summary using OpenAI
      const result = await generateSummary(url)
      
      // Create summary object
      const newSummary = {
        id: Date.now().toString(),
        title: result.title,
        url: url,
        summary: result.summary,
        keyFindings: result.keyFindings,
        dateCreated: new Date().toISOString()
      }

      // Save summary to database if user is logged in
      if (user?.id) {
        await saveSummary(user.id, newSummary)
      }

      // Update UI with new summary
      setSummary(newSummary)
      onSummaryCreated(newSummary)
      setStatus('success')
      setUrl('')

      // Increment user's summary count
      await incrementSummariesUsed()
    } catch (error) {
      console.error('Error generating summary:', error)
      setStatus('error')
      setErrorMessage(error.message || 'Failed to generate summary. Please try again.')
    }
  }

  const handleExport = (format) => {
    if (!summary) return
    
    let content = ''
    let filename = ''
    let mimeType = ''
    
    // Format content based on export type
    if (format === 'text') {
      content = `# ${summary.title}\n\n## Summary\n${summary.summary}\n\n## Key Findings\n${summary.keyFindings.map(f => `- ${f}`).join('\n')}\n\nSource: ${summary.url}\nGenerated by ScholarSift on ${new Date(summary.dateCreated).toLocaleDateString()}`
      filename = `${summary.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.txt`
      mimeType = 'text/plain'
    } else if (format === 'json') {
      content = JSON.stringify(summary, null, 2)
      filename = `${summary.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.json`
      mimeType = 'application/json'
    }
    
    // Create and download file
    const blob = new Blob([content], { type: mimeType })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="card">
      <div className="flex items-center gap-3 mb-6">
        <div className="p-2 bg-primary/10 rounded-md">
          <FileText className="h-6 w-6 text-primary" />
        </div>
        <div>
          <h2 className="text-2xl font-semibold text-gray-900">Summarize Paper</h2>
          <p className="text-gray-600">Enter a paper URL or DOI to get instant insights</p>
        </div>
      </div>

      <form onSubmit={handleSubmit} className="space-y-4">
        <div>
          <label htmlFor="paper-url" className="block text-sm font-medium text-gray-700 mb-2">
            Paper URL or DOI
          </label>
          <input
            id="paper-url"
            type="url"
            value={url}
            onChange={(e) => setUrl(e.target.value)}
            className="input"
            placeholder="https://arxiv.org/abs/1706.03762 or 10.1038/nature..."
            required
          />
        </div>

        <ActionStatus 
          status={status} 
          message={errorMessage || undefined}
        />

        <div className="flex gap-3">
          <button
            type="submit"
            disabled={status === 'pending' || !url.trim() || reachedLimit}
            className="btn-primary flex-1"
          >
            {status === 'pending' ? 'Generating Summary...' : 'Generate Summary'}
          </button>
        </div>

        {reachedLimit && (
          <div className="p-4 bg-warning/10 rounded-md">
            <p className="text-sm text-warning font-medium">
              You've reached your summary limit. Upgrade to continue summarizing papers.
            </p>
          </div>
        )}
      </form>

      {summary && (
        <div className="mt-8 p-6 bg-gray-50 rounded-lg animate-slide-up">
          <div className="flex items-start justify-between mb-4">
            <h3 className="text-xl font-semibold text-gray-900">{summary.title}</h3>
            <a
              href={summary.url}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-1 text-primary hover:text-primary/80 text-sm"
            >
              <ExternalLink className="h-4 w-4" />
              View Paper
            </a>
          </div>
          
          <div className="space-y-4">
            <div>
              <h4 className="font-semibold text-gray-900 mb-2">Summary</h4>
              <p className="text-gray-700 leading-relaxed">{summary.summary}</p>
            </div>
            
            <div>
              <h4 className="font-semibold text-gray-900 mb-2">Key Findings</h4>
              <ul className="space-y-1">
                {summary.keyFindings.map((finding, index) => (
                  <li key={index} className="flex items-start gap-2">
                    <span className="w-1.5 h-1.5 bg-primary rounded-full mt-2 flex-shrink-0" />
                    <span className="text-gray-700">{finding}</span>
                  </li>
                ))}
              </ul>
            </div>
            
            <div className="flex flex-wrap gap-2 pt-4 mt-4 border-t border-gray-200">
              <button
                onClick={() => handleExport('text')}
                className="flex items-center gap-1 px-3 py-1.5 bg-gray-100 hover:bg-gray-200 rounded-md text-sm text-gray-700"
              >
                <Download className="h-4 w-4" />
                Export as Text
              </button>
              
              <button
                onClick={() => handleExport('json')}
                className="flex items-center gap-1 px-3 py-1.5 bg-gray-100 hover:bg-gray-200 rounded-md text-sm text-gray-700"
              >
                <Download className="h-4 w-4" />
                Export as JSON
              </button>
              
              {user?.subscriptionTier === 'premium' && (
                <button
                  className="flex items-center gap-1 px-3 py-1.5 bg-primary/10 hover:bg-primary/20 rounded-md text-sm text-primary"
                >
                  <Share className="h-4 w-4" />
                  Share Summary
                </button>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
