import React, { useState, useEffect } from 'react'
import { Clock, ExternalLink, Trash2, Download, Search } from 'lucide-react'
import { useAuth } from '../context/AuthContext'
import { getUserSummaries, deleteSummary } from '../services/supabaseService'
import ActionStatus from './ActionStatus'

export default function RecentSummaries({ summaries: propSummaries, onSummaryDeleted }) {
  const [summaries, setSummaries] = useState(propSummaries || [])
  const [loading, setLoading] = useState(false)
  const [searchQuery, setSearchQuery] = useState('')
  const [status, setStatus] = useState('idle')
  const { user } = useAuth()

  // Fetch summaries from database when component mounts
  useEffect(() => {
    async function fetchSummaries() {
      if (!user?.id) return
      
      setLoading(true)
      try {
        const userSummaries = await getUserSummaries(user.id)
        // If we have summaries from props, merge them with database summaries
        // This ensures we show newly created summaries immediately
        if (propSummaries && propSummaries.length > 0) {
          // Combine and deduplicate by ID
          const combinedSummaries = [...propSummaries, ...userSummaries]
          const uniqueSummaries = Array.from(
            new Map(combinedSummaries.map(item => [item.id, item])).values()
          )
          setSummaries(uniqueSummaries)
        } else {
          setSummaries(userSummaries)
        }
      } catch (error) {
        console.error('Error fetching summaries:', error)
      } finally {
        setLoading(false)
      }
    }

    fetchSummaries()
  }, [user?.id, propSummaries])

  // Update summaries when prop summaries change
  useEffect(() => {
    if (propSummaries) {
      setSummaries(prev => {
        // Combine and deduplicate
        const combined = [...propSummaries, ...prev]
        return Array.from(new Map(combined.map(item => [item.id, item])).values())
      })
    }
  }, [propSummaries])

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric'
    })
  }

  const handleDeleteSummary = async (summaryId) => {
    if (!user?.id) return
    
    setStatus('pending')
    try {
      const result = await deleteSummary(user.id, summaryId)
      if (result.success) {
        // Remove from local state
        setSummaries(prev => prev.filter(s => s.id !== summaryId))
        // Notify parent component if callback provided
        if (onSummaryDeleted) {
          onSummaryDeleted(summaryId)
        }
        setStatus('success')
      } else {
        throw new Error(result.error || 'Failed to delete summary')
      }
    } catch (error) {
      console.error('Error deleting summary:', error)
      setStatus('error')
    }
  }

  const handleExport = (summary, format) => {
    if (!summary) return
    
    let content = ''
    let filename = ''
    let mimeType = ''
    
    // Format content based on export type
    if (format === 'text') {
      content = `# ${summary.title}\n\n## Summary\n${summary.summary}\n\n## Key Findings\n${summary.keyFindings.map(f => `- ${f}`).join('\n')}\n\nSource: ${summary.url}\nGenerated by ScholarSift on ${new Date(summary.dateCreated).toLocaleDateString()}`
      filename = `${summary.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.txt`
      mimeType = 'text/plain'
    } else if (format === 'json') {
      content = JSON.stringify(summary, null, 2)
      filename = `${summary.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.json`
      mimeType = 'application/json'
    }
    
    // Create and download file
    const blob = new Blob([content], { type: mimeType })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  // Filter summaries based on search query
  const filteredSummaries = searchQuery.trim() 
    ? summaries.filter(summary => 
        summary.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
        summary.summary.toLowerCase().includes(searchQuery.toLowerCase())
      )
    : summaries

  return (
    <div className="card">
      <div className="flex items-center gap-3 mb-6">
        <div className="p-2 bg-secondary/10 rounded-md">
          <Clock className="h-6 w-6 text-secondary" />
        </div>
        <div>
          <h2 className="text-2xl font-semibold text-gray-900">Recent Summaries</h2>
          <p className="text-gray-600">Your previously generated paper insights</p>
        </div>
      </div>

      {/* Search input */}
      {summaries.length > 0 && (
        <div className="mb-4 relative">
          <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
            <Search className="h-4 w-4 text-gray-400" />
          </div>
          <input
            type="text"
            placeholder="Search summaries..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="input pl-10"
          />
        </div>
      )}

      <ActionStatus status={status} />

      {loading ? (
        <div className="text-center py-8">
          <p className="text-gray-500">Loading summaries...</p>
        </div>
      ) : filteredSummaries.length === 0 ? (
        <div className="text-center py-8">
          <p className="text-gray-500">
            {searchQuery.trim() 
              ? 'No summaries match your search query.' 
              : 'No summaries yet. Generate your first summary above!'}
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          {filteredSummaries.map((summary) => (
            <div key={summary.id} className="p-4 border border-gray-200 rounded-lg hover:shadow-md transition-shadow">
              <div className="flex items-start justify-between mb-3">
                <h3 className="font-semibold text-gray-900 line-clamp-2">{summary.title}</h3>
                <div className="flex items-center gap-2 ml-4">
                  <span className="text-sm text-gray-500">{formatDate(summary.dateCreated)}</span>
                  <a
                    href={summary.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-primary hover:text-primary/80"
                    title="View original paper"
                  >
                    <ExternalLink className="h-4 w-4" />
                  </a>
                </div>
              </div>
              
              <p className="text-gray-700 text-sm mb-3 line-clamp-3">{summary.summary}</p>
              
              <div className="flex flex-wrap gap-2 mb-3">
                {summary.keyFindings.slice(0, 2).map((finding, index) => (
                  <span
                    key={index}
                    className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-primary/10 text-primary"
                  >
                    {finding.length > 50 ? finding.substring(0, 50) + '...' : finding}
                  </span>
                ))}
                {summary.keyFindings.length > 2 && (
                  <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-gray-100 text-gray-600">
                    +{summary.keyFindings.length - 2} more
                  </span>
                )}
              </div>
              
              <div className="flex justify-end gap-2">
                <button
                  onClick={() => handleExport(summary, 'text')}
                  className="p-1 text-gray-500 hover:text-gray-700"
                  title="Export as text"
                >
                  <Download className="h-4 w-4" />
                </button>
                <button
                  onClick={() => handleDeleteSummary(summary.id)}
                  className="p-1 text-gray-500 hover:text-error"
                  title="Delete summary"
                >
                  <Trash2 className="h-4 w-4" />
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
